title: Lotus Oak Foundation
email: contact@lotusoak.org
description: >- # this means to ignore newlines until "baseurl:"
  Blending traditional philanthropy with innovative social venture approaches
baseurl: "" # leave empty for custom domain
url: "https://lotusoak.org" # your custom domain

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Show post excerpts on home page
show_excerpts: true

# Navigation Structure
nav_sections:
  - title: About Us
    subitems:
      - title: Our Vision
        url: /vision
      - title: Our Team
        url: /team
      - title: Our Impact
        url: /impact
  - title: Get Involved
    subitems:
      - title: DAF Explained
        url: /daf-explained
      - title: Partner With Us
        url: /partnership
  - title: Focus Areas
    subitems:
      - title: Education
        url: /education
      - title: Healthcare
        url: /healthcare
      - title: Environmental Conservation
        url: /environment
      - title: Cultural Renewal
        url: /culture
  - title: Resources
    subitems:
      - title: Blog
        url: /blog
      - title: News
        url: /news
      - title: Reports
        url: /reports
  - title: Contact
    url: /contact

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      author: "Lotus Oak Team"
      show_sidebar: true
      show_breadcrumbs: true 