title: Lotus Oak Foundation
email: contact@lotusoak.org
description: >- # this means to ignore newlines until "baseurl:"
  Blending traditional philanthropy with innovative social venture approaches
baseurl: "" # leave empty for custom domain
url: "https://lotusoak.org" # your custom domain

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag

# Show post excerpts on home page
show_excerpts: true

defaults:
  - scope:
      path: ""
    values:
      nav_sections: "{{ site.data.navigation.nav_sections }}"
      nav_external_links: "{{ site.data.navigation.nav_external_links }}" 